# Generated by Django 4.1.3 on 2022-11-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggeditem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taggeditem',
            name='tag',
        ),
        migrations.DeleteModel(
            name='LikedItem',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TaggedItem',
        ),
    ]
