# Generated by Django 4.1.3 on 2022-11-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_address_zip_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='playground__last_na_857630_idx',
            old_name='store_custo_last_na_e6a359_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='playground_customers',
        ),
    ]
