# Generated by Django 4.1.3 on 2022-11-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_rename_store_custo_last_na_e6a359_idx_playground__last_na_857630_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='playground__last_na_857630_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
